Added: parameters for customizing target machine's spec (cpu & memory)
DimensionDataResearch/docker-machine-driver-ddcloud pull request #13
Opened 2018-05-11 18:44 UTC by tmuskal

added support for:
* `ddcloud-memorygb` - The amount of RAM in GB for the target machine. (Default 4GB)
* `ddcloud-cpucount` - The amount of CPUs for the target machine. (Default: 2)
* `ddcloud-corespersocket` - The amount of cores per socket for the target machine. (Default: 2)

2018-05-11 21:26 UTC, tintoy commented
Thanks! Will look at this first thing Monday :)

2018-05-11 22:29 UTC, tmuskal commented
actually, it doesn't work for me for some reason. the API seem to ignore those parameters in the datacenter i'm using. but it seem to be outside the scope of this project.

2018-05-11 23:50 UTC, tintoy commented
If you set the `MCP_EXTENDED_LOGGING` environment variable equal to `1`, the client will log the URL and body for each CloudControl API request / response.

2018-05-13 04:13 UTC, tintoy requested changes
Apart from the `image.ApplyTo()` issue, this looks great - thanks for contributing!

2018-05-13 04:13 UTC, tintoy commented on client.go
> +	// Customise memory and / or CPU (if required).
Ah, this needs to happen _after_ the image is applied below (image will already specify these values so it will override the values you're supplying here).

2018-05-13 04:13 UTC, tintoy commented on client.go
> +	// Customise memory and / or CPU (if required).
See [here](https://github.com/DimensionDataResearch/go-dd-cloud-compute/blob/231d5c08270e9b55b822287f7f4c07c93f90fafa/compute/os_images.go#L83-L91) for details.

2018-05-17 02:28 UTC, tmuskal commented
thanks.
moved the added part after image.ApplyTo.

2018-05-17 02:53 UTC, tintoy approved these changes

2018-05-17 02:54 UTC, merged

2018-05-17 03:01 UTC, tintoy commented
@tmuskal - https://github.com/DimensionDataResearch/docker-machine-driver-ddcloud/releases/tag/v0.9.5

2018-05-17 04:20 UTC, tmuskal commented
awesome. tested and it even works now :)

2018-05-17 04:24 UTC, tmuskal commented
actually. this kind of broke something. you can't use the default settings of the image now. 

i guess it is a desired functionality...

2018-05-17 04:29 UTC, tintoy commented
Eek! Good catch, yes, need to fix that. Maybe if we set the parameter defaults to -1 and only override image values if not - 1?

2018-05-17 04:31 UTC, tmuskal commented
https://github.com/DimensionDataResearch/docker-machine-driver-ddcloud/pull/14